# Generated by Django 5.2.7 on 2025-10-28 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issue",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "В работе"),
                    ("in_progress", "В процессе"),
                    ("done", "Готово"),
                    ("cancelled", "Отменено"),
                ],
                default="open",
                max_length=20,
            ),
        ),
    ]
