# Generated by Django 5.2.7 on 2026-04-29 07:59

import django.core.validators
import issues.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0005_checklistitem_issueactivity_issuerelation_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attachment",
            name="file",
            field=models.FileField(
                upload_to="attachments/%Y/%m/%d/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=[
                            "pdf",
                            "doc",
                            "docx",
                            "xls",
                            "xlsx",
                            "ppt",
                            "pptx",
                            "odt",
                            "ods",
                            "txt",
                            "md",
                            "csv",
                            "log",
                            "jpg",
                            "jpeg",
                            "png",
                            "gif",
                            "webp",
                            "svg",
                            "zip",
                            "rar",
                            "7z",
                            "tar",
                            "gz",
                            "mp3",
                            "mp4",
                            "mov",
                            "avi",
                            "webm",
                        ]
                    ),
                    issues.models.validate_file_size,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="invitation",
            name="role",
            field=models.CharField(
                choices=[
                    ("viewer", "Спостерігач"),
                    ("member", "Учасник"),
                    ("manager", "Менеджер"),
                    ("owner", "Власник"),
                ],
                default="member",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="issue",
            name="priority",
            field=models.CharField(
                choices=[
                    ("low", "Низький"),
                    ("medium", "Середній"),
                    ("high", "Високий"),
                ],
                db_index=True,
                default="medium",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="issue",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Відкрито"),
                    ("in_progress", "В процесі"),
                    ("done", "Готово"),
                    ("cancelled", "Скасовано"),
                ],
                db_index=True,
                default="open",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="issuerelation",
            name="relation_type",
            field=models.CharField(
                choices=[
                    ("blocks", "Блокує"),
                    ("blocked_by", "Заблоковано"),
                    ("relates_to", "Пов'язано з"),
                    ("duplicate_of", "Дублікат"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="projectmembership",
            name="role",
            field=models.CharField(
                choices=[
                    ("viewer", "Спостерігач"),
                    ("member", "Учасник"),
                    ("manager", "Менеджер"),
                    ("owner", "Власник"),
                ],
                default="member",
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="issuerelation",
            constraint=models.CheckConstraint(
                condition=models.Q(("from_issue", models.F("to_issue")), _negated=True),
                name="issue_relation_no_self_reference",
            ),
        ),
    ]
