# Generated by Django 5.2.7 on 2026-04-29 15:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0008_alter_project_members"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CommentReaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "emoji",
                    models.CharField(
                        choices=[
                            ("👍", "Подобається"),
                            ("❤️", "Серце"),
                            ("🚀", "Ракета"),
                            ("🎉", "Святкування"),
                            ("😄", "Сміх"),
                            ("👀", "Очі"),
                        ],
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="EmailToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("token", models.CharField(db_index=True, max_length=64, unique=True)),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("confirm_email", "Підтвердження пошти"),
                            ("reset_password", "Скидання пароля"),
                        ],
                        max_length=20,
                    ),
                ),
                ("expires_at", models.DateTimeField()),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("email_verified", models.BooleanField(default=False)),
                ("email_verified_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="project",
            name="archived_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="is_archived",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["is_archived", "-created_at"], name="issues_proj_is_arch_9e6992_idx"
            ),
        ),
        migrations.AddField(
            model_name="commentreaction",
            name="comment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reactions",
                to="issues.comment",
            ),
        ),
        migrations.AddField(
            model_name="commentreaction",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reactions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="emailtoken",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="email_tokens",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="commentreaction",
            index=models.Index(fields=["comment", "emoji"], name="issues_comm_comment_022858_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="commentreaction",
            unique_together={("comment", "user", "emoji")},
        ),
        migrations.AddIndex(
            model_name="emailtoken",
            index=models.Index(fields=["user", "purpose"], name="issues_emai_user_id_f5e664_idx"),
        ),
    ]
