# Generated by Django 5.2.7 on 2026-05-06 07:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0009_commentreaction_emailtoken_userprofile_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TestCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(db_index=True, max_length=255)),
                ("preconditions", models.TextField(blank=True)),
                ("steps", models.JSONField(blank=True, default=list)),
                ("expected_result", models.TextField(blank=True)),
                (
                    "type",
                    models.CharField(
                        choices=[("manual", "Manual"), ("automated", "Automated")],
                        default="manual",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("critical", "Critical"),
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                (
                    "automation_link",
                    models.URLField(blank=True, help_text="URL до Playwright/Cypress тесту"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TestResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("pass", "Pass"),
                            ("fail", "Fail"),
                            ("blocked", "Blocked"),
                            ("skip", "Skip"),
                            ("pending", "Pending"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("note", models.TextField(blank=True)),
                ("executed_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="TestRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "environment",
                    models.CharField(
                        blank=True, help_text="Production / Staging / ...", max_length=80
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("aborted", "Aborted"),
                        ],
                        default="planned",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TestSuite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="TimeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("minutes", models.PositiveIntegerField()),
                ("note", models.CharField(blank=True, max_length=255)),
                ("logged_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "ordering": ["-logged_at"],
            },
        ),
        migrations.CreateModel(
            name="Webhook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("url", models.URLField()),
                (
                    "events",
                    models.JSONField(default=list, help_text="Список eventів зі списку EVENTS"),
                ),
                (
                    "secret",
                    models.CharField(
                        blank=True,
                        help_text="Опційний secret для HMAC-підпису payload",
                        max_length=128,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_called_at", models.DateTimeField(blank=True, null=True)),
                ("last_status_code", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="WebhookDelivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("event", models.CharField(max_length=64)),
                ("payload", models.JSONField(default=dict)),
                ("status_code", models.IntegerField(blank=True, null=True)),
                ("response_body", models.TextField(blank=True)),
                ("error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="issue",
            name="archived_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="issue",
            name="custom_fields",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="issue",
            name="is_archived",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="issue",
            name="time_spent_minutes",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="onboarding_done",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="totp_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="totp_secret",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.CreateModel(
            name="ApiToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Описова назва (CI deploy, my-script)", max_length=80
                    ),
                ),
                ("key", models.CharField(db_index=True, max_length=64, unique=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="IntegrationConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("github", "GitHub"), ("gitlab", "GitLab"), ("slack", "Slack")],
                        max_length=20,
                    ),
                ),
                ("config", models.JSONField(default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="integrations",
                        to="issues.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IssueTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "description_template",
                    models.TextField(
                        help_text="Markdown-шаблон для опису задачі (наприклад з кроками репро)"
                    ),
                ),
                (
                    "default_priority",
                    models.CharField(
                        choices=[("low", "Низький"), ("medium", "Середній"), ("high", "Високий")],
                        default="medium",
                        max_length=20,
                    ),
                ),
                (
                    "custom_fields_schema",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Список полів зі схемою [{name, label, type: text|number|select, options?}]",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "default_labels",
                    models.ManyToManyField(blank=True, related_name="templates", to="issues.label"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        help_text="Якщо null — глобальний шаблон, доступний у всіх проєктах",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="issue_templates",
                        to="issues.project",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="LoginEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("username_attempted", models.CharField(blank=True, max_length=150)),
                ("success", models.BooleanField(default=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=255)),
                (
                    "method",
                    models.CharField(
                        default="password",
                        help_text="password / oauth_google / oauth_github / token",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="login_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SavedFilter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("params", models.JSONField(default=dict)),
                ("is_pinned", models.BooleanField(default=False)),
                ("icon", models.CharField(blank=True, default="Filter", max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_filters",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-is_pinned", "name"],
            },
        ),
        migrations.CreateModel(
            name="Sprint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("goal", models.TextField(blank=True)),
                ("starts_at", models.DateField()),
                ("ends_at", models.DateField()),
                ("is_active", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sprints",
                        to="issues.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-starts_at"],
            },
        ),
        migrations.AddField(
            model_name="issue",
            name="sprint",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="issues",
                to="issues.sprint",
            ),
        ),
        migrations.AddIndex(
            model_name="issue",
            index=models.Index(
                fields=["is_archived", "-created_at"], name="issues_issu_is_arch_5806a9_idx"
            ),
        ),
        migrations.AddField(
            model_name="testcase",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_test_cases",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="testresult",
            name="executed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="test_executions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="testresult",
            name="related_issue",
            field=models.ForeignKey(
                blank=True,
                help_text="Якщо fail — пов'язаний баг",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="test_failures",
                to="issues.issue",
            ),
        ),
        migrations.AddField(
            model_name="testresult",
            name="test_case",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="results",
                to="issues.testcase",
            ),
        ),
        migrations.AddField(
            model_name="testrun",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_test_runs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="testrun",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="test_runs",
                to="issues.project",
            ),
        ),
        migrations.AddField(
            model_name="testrun",
            name="test_cases",
            field=models.ManyToManyField(
                blank=True, related_name="test_runs", to="issues.testcase"
            ),
        ),
        migrations.AddField(
            model_name="testresult",
            name="run",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="results",
                to="issues.testrun",
            ),
        ),
        migrations.AddField(
            model_name="testsuite",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="test_suites",
                to="issues.project",
            ),
        ),
        migrations.AddField(
            model_name="testcase",
            name="suite",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="test_cases",
                to="issues.testsuite",
            ),
        ),
        migrations.AddField(
            model_name="timelog",
            name="issue",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="time_logs",
                to="issues.issue",
            ),
        ),
        migrations.AddField(
            model_name="timelog",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="time_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="webhook",
            name="project",
            field=models.ForeignKey(
                blank=True,
                help_text="null — глобальний webhook на всі проєкти",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="webhooks",
                to="issues.project",
            ),
        ),
        migrations.AddField(
            model_name="webhookdelivery",
            name="webhook",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="deliveries",
                to="issues.webhook",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="integrationconfig",
            unique_together={("project", "kind")},
        ),
        migrations.AddIndex(
            model_name="loginevent",
            index=models.Index(
                fields=["user", "-created_at"], name="issues_logi_user_id_bb8abb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sprint",
            index=models.Index(
                fields=["project", "-starts_at"], name="issues_spri_project_5cd7a7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sprint",
            index=models.Index(fields=["is_active"], name="issues_spri_is_acti_6c654f_idx"),
        ),
        migrations.AddIndex(
            model_name="testresult",
            index=models.Index(fields=["run", "result"], name="issues_test_run_id_98f852_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="testresult",
            unique_together={("run", "test_case")},
        ),
        migrations.AddIndex(
            model_name="testcase",
            index=models.Index(
                fields=["suite", "-created_at"], name="issues_test_suite_i_658ac0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="testcase",
            index=models.Index(fields=["type"], name="issues_test_type_ad8063_idx"),
        ),
        migrations.AddIndex(
            model_name="timelog",
            index=models.Index(
                fields=["issue", "-logged_at"], name="issues_time_issue_i_18f447_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="timelog",
            index=models.Index(
                fields=["user", "-logged_at"], name="issues_time_user_id_e5b420_idx"
            ),
        ),
    ]
