# Generated by Django 5.2.11 on 2026-05-09 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0010_testcase_testresult_testrun_testsuite_timelog_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issue",
            name="priority",
            field=models.CharField(
                choices=[
                    ("low", "Низький"),
                    ("medium", "Середній"),
                    ("high", "Високий"),
                    ("critical", "Критичний"),
                ],
                db_index=True,
                default="medium",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="issuetemplate",
            name="default_priority",
            field=models.CharField(
                choices=[
                    ("low", "Низький"),
                    ("medium", "Середній"),
                    ("high", "Високий"),
                    ("critical", "Критичний"),
                ],
                default="medium",
                max_length=20,
            ),
        ),
    ]
