# Generated by Django 5.2.11 on 2026-05-09 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0011_alter_issue_priority_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="color",
            field=models.CharField(default="#5E6AD2", max_length=9),
        ),
        migrations.AddField(
            model_name="project",
            name="icon",
            field=models.CharField(default="Layout", max_length=32),
        ),
        migrations.AddField(
            model_name="project",
            name="key",
            field=models.CharField(blank=True, db_index=True, max_length=10),
        ),
        migrations.AddField(
            model_name="project",
            name="visibility",
            field=models.CharField(
                choices=[("team", "Команда"), ("org", "Уся організація"), ("private", "Приватний")],
                default="team",
                max_length=10,
            ),
        ),
    ]
