# Generated by Django 5.2.11 on 2026-05-09 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0012_project_color_project_icon_project_key_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="auto_join_domain",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="project",
            name="industry",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="project",
            name="region",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="project",
            name="slug",
            field=models.SlugField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="project",
            name="team_size",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
