# Generated by Django 5.2.11 on 2026-05-09 20:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0013_project_auto_join_domain_project_industry_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="auto_join_domain",
        ),
        migrations.RemoveField(
            model_name="project",
            name="industry",
        ),
        migrations.RemoveField(
            model_name="project",
            name="region",
        ),
        migrations.RemoveField(
            model_name="project",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="project",
            name="team_size",
        ),
        migrations.CreateModel(
            name="Workspace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=200)),
                ("slug", models.SlugField(max_length=64, unique=True)),
                ("color", models.CharField(default="#5E6AD2", max_length=9)),
                ("team_size", models.CharField(blank=True, max_length=20)),
                ("industry", models.CharField(blank=True, max_length=20)),
                ("region", models.CharField(blank=True, max_length=10)),
                ("auto_join_domain", models.BooleanField(default=False)),
                ("domain", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "members",
                    models.ManyToManyField(
                        blank=True, related_name="workspaces", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_workspaces",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="project",
            name="workspace",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="projects",
                to="issues.workspace",
            ),
        ),
    ]
