# Generated by Django 5.2.11 on 2026-05-10 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0014_remove_project_auto_join_domain_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=16, unique=True)),
                ("label", models.CharField(max_length=120)),
                ("icon", models.CharField(blank=True, max_length=8)),
                ("sort_order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("is_default", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["sort_order", "label"],
            },
        ),
    ]
