# Generated by Django 5.2.11 on 2026-05-10 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0017_remove_project_workspace_project_workspaces"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkflowStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("key", models.CharField(db_index=True, max_length=32)),
                ("label", models.CharField(max_length=64)),
                ("color", models.CharField(default="var(--st-open-dot)", max_length=24)),
                ("sort_order", models.IntegerField(default=0)),
                ("is_default", models.BooleanField(default=False)),
                (
                    "is_done",
                    models.BooleanField(default=False, help_text="Чи статус вважається завершеним"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workflow_statuses",
                        to="issues.project",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "id"],
                "unique_together": {("project", "key")},
            },
        ),
    ]
