# Generated by Django 5.2.11 on 2026-05-10 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0018_workflowstatus"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="workflow_status",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="issues",
                to="issues.workflowstatus",
            ),
        ),
    ]
