# Generated by Django 5.2.11 on 2026-05-10 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0020_seed_workflows_and_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="avatars/"),
        ),
    ]
