# Generated by Django 5.2.11 on 2026-05-10 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0021_userprofile_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="testresult",
            name="case_preconditions_snapshot",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="testresult",
            name="case_steps_snapshot",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="testresult",
            name="case_title_snapshot",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
