# Generated by Django 5.2.7 on 2026-05-11 17:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0023_sync_workspace_members"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="actor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="actor_notifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="kind",
            field=models.CharField(
                choices=[
                    ("mention", "Згадка"),
                    ("assigned", "Призначено"),
                    ("comment", "Коментар"),
                    ("review", "Запит на ревʼю"),
                    ("fail", "Невдалий тест"),
                    ("closed", "Закрито"),
                    ("other", "Інше"),
                ],
                db_index=True,
                default="other",
                max_length=16,
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(fields=["user", "kind"], name="issues_noti_user_id_4167b9_idx"),
        ),
    ]
