# Generated by Django 5.2.11 on 2026-05-12 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0024_notification_kind_actor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timelog",
            name="note",
            field=models.TextField(blank=True),
        ),
    ]
