# Generated by Django 5.2.11 on 2026-05-12 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0025_alter_timelog_note"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChangelogEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("version", models.CharField(help_text="Напр. 4.18.0", max_length=50)),
                ("release_date", models.DateField()),
                (
                    "tag",
                    models.CharField(
                        choices=[
                            ("major", "Major"),
                            ("minor", "Minor"),
                            ("patch", "Patch"),
                            ("security", "Security"),
                        ],
                        default="minor",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("summary", models.TextField(blank=True)),
                ("changes", models.JSONField(blank=True, default=list)),
                ("is_published", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-release_date", "-id"],
            },
        ),
    ]
