# Generated by Django 5.2.11 on 2026-05-13 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0026_changelogentry"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChangelogSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("email", models.EmailField(db_index=True, max_length=254, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
