# Generated by Django 5.2.11 on 2026-05-13 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0027_changelogsubscription"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoadmapItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Заплановано"),
                            ("in_progress", "У роботі"),
                            ("done", "Готово"),
                            ("cancelled", "Скасовано"),
                        ],
                        db_index=True,
                        default="planned",
                        max_length=20,
                    ),
                ),
                ("quarter", models.CharField(blank=True, help_text="Напр. Q3 2026", max_length=20)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["sort_order", "-created_at"],
            },
        ),
    ]
