# Generated by Django 5.2.11 on 2026-05-13 07:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0029_changelogreaction"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SupportSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "intro_text",
                    models.CharField(
                        default="Зазвичай відповідаємо за 4 години у робочий час", max_length=255
                    ),
                ),
                (
                    "status_kind",
                    models.CharField(
                        choices=[
                            ("operational", "Усі системи працюють"),
                            ("degraded", "Часткова деградація"),
                            ("down", "Серйозна аварія"),
                        ],
                        default="operational",
                        max_length=20,
                    ),
                ),
                ("status_text", models.CharField(default="усі системи працюють", max_length=120)),
                (
                    "email",
                    models.EmailField(
                        blank=True, default="support@bugtracker.local", max_length=254
                    ),
                ),
                (
                    "email_response_time",
                    models.CharField(blank=True, default="Відповідь до 4 год", max_length=80),
                ),
                (
                    "chat_hours",
                    models.CharField(blank=True, default="Пн–Пт, 9:00–18:00", max_length=120),
                ),
                ("community_link", models.URLField(blank=True, default="")),
                (
                    "community_label",
                    models.CharField(blank=True, default="Спільнота у Slack", max_length=120),
                ),
                ("github_link", models.URLField(blank=True, default="")),
                (
                    "github_label",
                    models.CharField(blank=True, default="github.com", max_length=120),
                ),
                (
                    "business_hours_weekday",
                    models.CharField(blank=True, default="Пн–Пт · 9:00–18:00 EET", max_length=120),
                ),
                (
                    "business_hours_weekend",
                    models.CharField(
                        blank=True, default="Сб–Нд · тільки критичні (Enterprise)", max_length=120
                    ),
                ),
                (
                    "categories",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Список об'єктів {key, label, description}",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Support settings",
                "verbose_name_plural": "Support settings",
            },
        ),
        migrations.CreateModel(
            name="SupportTicket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("category", models.CharField(max_length=40)),
                ("subject", models.CharField(max_length=255)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Низький"),
                            ("normal", "Звичайний"),
                            ("high", "Високий"),
                            ("urgent", "Терміновий"),
                        ],
                        default="normal",
                        max_length=10,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Відкрито"),
                            ("in_progress", "В роботі"),
                            ("closed", "Закрито"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=20,
                    ),
                ),
                ("submitted_email", models.EmailField(blank=True, max_length=254)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="support_tickets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
