# Generated by Django 5.2.11 on 2026-05-13 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0031_supportagentpermission_supportcomment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supportsettings",
            name="status_kind",
            field=models.CharField(
                choices=[
                    ("operational", "Усі системи працюють"),
                    ("maintenance", "Технічне обслуговування"),
                    ("degraded", "Часткова деградація"),
                    ("minor", "Незначні збої"),
                    ("major", "Серйозні проблеми"),
                    ("down", "Серйозна аварія"),
                    ("investigating", "Розслідуємо інцидент"),
                    ("resolved", "Інцидент усунено"),
                ],
                default="operational",
                max_length=20,
            ),
        ),
    ]
