# Generated by Django 5.2.11 on 2026-05-14 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0032_alter_supportsettings_status_kind"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="kind",
            field=models.CharField(
                choices=[
                    ("mention", "Згадка"),
                    ("assigned", "Призначено"),
                    ("comment", "Коментар"),
                    ("review", "Запит на ревʼю"),
                    ("fail", "Невдалий тест"),
                    ("closed", "Закрито"),
                    ("support_new", "Нове звернення у підтримку"),
                    ("support_reply", "Відповідь у зверненні"),
                    ("other", "Інше"),
                ],
                db_index=True,
                default="other",
                max_length=16,
            ),
        ),
    ]
