# Generated by Django 5.2.11 on 2026-05-18 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0034_pg_trgm"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="changelogentry",
            options={"ordering": ["-created_at", "-id"]},
        ),
    ]
