# Generated by Django 5.2.11 on 2026-05-26 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0036_commentattachment"),
    ]

    operations = [
        migrations.AddField(
            model_name="sprint",
            name="capacity_sp",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
