# Generated by Django 5.2.11 on 2026-05-26 12:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0037_sprint_capacity_sp"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="issuetemplate",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="issuetemplate",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="authored_templates",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="issuetemplate",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="issuetemplate",
            name="kind",
            field=models.CharField(
                choices=[("bug", "Bug"), ("test_case", "Test case"), ("test_run", "Test run")],
                db_index=True,
                default="bug",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="issuetemplate",
            name="tags",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="issuetemplate",
            name="usage_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="issuetemplate",
            name="visibility",
            field=models.CharField(
                choices=[("me", "Тільки я"), ("space", "Простір"), ("public", "Публічний")],
                default="space",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="issuetemplate",
            name="custom_fields_schema",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Список полів зі схемою [{name, label, type: text|number|select, options?, required?}]",
            ),
        ),
        migrations.AlterField(
            model_name="issuetemplate",
            name="description_template",
            field=models.TextField(
                blank=True, help_text="Markdown-шаблон для опису задачі (наприклад з кроками репро)"
            ),
        ),
    ]
