# Generated by Django 5.2.7 on 2026-05-02 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LandingFaqItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("position", models.PositiveIntegerField(db_index=True, default=0)),
                ("is_visible", models.BooleanField(default=True)),
                ("question", models.CharField(max_length=200)),
                ("answer", models.TextField()),
            ],
            options={
                "verbose_name": "FAQ",
                "verbose_name_plural": "FAQ",
                "ordering": ["position"],
            },
        ),
        migrations.CreateModel(
            name="LandingFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("position", models.PositiveIntegerField(db_index=True, default=0)),
                ("is_visible", models.BooleanField(default=True)),
                ("title", models.CharField(max_length=120)),
                ("description", models.TextField()),
                (
                    "icon",
                    models.CharField(
                        choices=[
                            ("Bug", "🐛 Bug"),
                            ("Beaker", "🧪 Beaker"),
                            ("Play", "▶ Play"),
                            ("Layout", "▦ Layout"),
                            ("Chart", "📊 Chart"),
                            ("Comment", "💬 Comment"),
                            ("Bell", "🔔 Bell"),
                            ("Lightning", "⚡ Lightning"),
                            ("AI", "✨ AI"),
                            ("User", "👤 User"),
                            ("Users", "👥 Users"),
                            ("Github", "Github"),
                            ("Slack", "Slack"),
                            ("Spark", "✦ Spark"),
                            ("Star", "★ Star"),
                            ("Globe", "🌐 Globe"),
                            ("Refresh", "↻ Refresh"),
                            ("Settings", "⚙ Settings"),
                            ("Lock", "🔒 Lock"),
                            ("Activity", "📈 Activity"),
                        ],
                        default="Bug",
                        max_length=32,
                    ),
                ),
                (
                    "color_variant",
                    models.CharField(
                        choices=[
                            ("accent", "Акцент (фіолетовий)"),
                            ("resolved", "Зелений"),
                            ("progress", "Жовтий"),
                            ("blocked", "Пурпуровий"),
                            ("open", "Червоний"),
                            ("closed", "Сірий"),
                        ],
                        default="accent",
                        max_length=20,
                    ),
                ),
                ("featured", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Можливість",
                "verbose_name_plural": "Можливості",
                "ordering": ["position"],
            },
        ),
        migrations.CreateModel(
            name="LandingHero",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "eyebrow_badge",
                    models.CharField(
                        default="NEW", help_text="Бейдж зліва в eyebrow", max_length=32
                    ),
                ),
                (
                    "eyebrow_text",
                    models.CharField(
                        default="AI-резюме багів",
                        help_text="Текст біля бейджа в eyebrow",
                        max_length=120,
                    ),
                ),
                (
                    "eyebrow_version",
                    models.CharField(
                        blank=True,
                        default="v2.0",
                        help_text="Версія справа в eyebrow",
                        max_length=32,
                    ),
                ),
                ("title_a", models.CharField(default="Баг-трекер,", max_length=200)),
                ("title_accent", models.CharField(default="що ловить дефекти", max_length=200)),
                (
                    "title_b",
                    models.CharField(default="до того, як їх побачить юзер.", max_length=200),
                ),
                (
                    "lede",
                    models.TextField(
                        default="BugTracker об'єднує задачі, коментарі та сповіщення у єдиному робочому просторі. Без зайвого, без чату-смітника, без втрати контексту."
                    ),
                ),
                ("primary_cta_text", models.CharField(default="Почати безкоштовно", max_length=64)),
                ("primary_cta_link", models.CharField(default="/register", max_length=128)),
                (
                    "secondary_cta_text",
                    models.CharField(default="Подивитися застосунок", max_length=64),
                ),
                ("secondary_cta_link", models.CharField(default="/login", max_length=128)),
                (
                    "foot_text_1",
                    models.CharField(default="Безкоштовно для невеликих команд", max_length=80),
                ),
                ("foot_text_2", models.CharField(default="Без картки", max_length=80)),
                ("foot_text_3", models.CharField(default="SOC 2 · GDPR", max_length=80)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Hero блок",
                "verbose_name_plural": "Hero блок",
            },
        ),
        migrations.CreateModel(
            name="LandingIntegration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("position", models.PositiveIntegerField(db_index=True, default=0)),
                ("is_visible", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=64)),
                ("mark", models.CharField(default="??", max_length=4)),
                ("color", models.CharField(default="#5E6AD2", max_length=7)),
            ],
            options={
                "verbose_name": "Інтеграція",
                "verbose_name_plural": "Інтеграції",
                "ordering": ["position"],
            },
        ),
        migrations.CreateModel(
            name="LandingMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("position", models.PositiveIntegerField(db_index=True, default=0)),
                ("is_visible", models.BooleanField(default=True)),
                ("value", models.CharField(help_text="Наприклад: 3.2× або 99.98%", max_length=32)),
                ("label", models.CharField(max_length=120)),
            ],
            options={
                "verbose_name": "Метрика",
                "verbose_name_plural": "Метрики",
                "ordering": ["position"],
            },
        ),
        migrations.CreateModel(
            name="LandingSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("show_features", models.BooleanField(default=True)),
                ("show_use_cases", models.BooleanField(default=True)),
                ("show_metrics", models.BooleanField(default=True)),
                ("show_integrations", models.BooleanField(default=True)),
                ("show_testimonials", models.BooleanField(default=True)),
                ("show_faq", models.BooleanField(default=True)),
                ("show_cta_strip", models.BooleanField(default=True)),
                ("features_kicker", models.CharField(default="Можливості", max_length=64)),
                (
                    "features_title",
                    models.CharField(
                        default="Усе, що треба команді — і нічого зайвого", max_length=200
                    ),
                ),
                (
                    "features_subtitle",
                    models.TextField(
                        default="Фокус на трьох речах: фіксація задач, керування коментарями та сповіщеннями. Без overhead'у Jira і без хаосу Trello."
                    ),
                ),
                ("use_cases_kicker", models.CharField(default="Для кого", max_length=64)),
                (
                    "use_cases_title",
                    models.CharField(default="Підходить вашій ролі", max_length=200),
                ),
                (
                    "use_cases_subtitle",
                    models.TextField(
                        default="BugTracker приходить у команду без революцій — і одразу прибирає три-чотири інші вкладки з браузера."
                    ),
                ),
                ("integrations_kicker", models.CharField(default="Інтеграції", max_length=64)),
                (
                    "integrations_title",
                    models.CharField(default="Підключається до того, що вже є", max_length=200),
                ),
                (
                    "integrations_subtitle",
                    models.TextField(
                        default="30+ інтеграцій з SCM, чатами, CI/CD та observability. REST API і webhooks — для всього іншого."
                    ),
                ),
                ("testimonials_kicker", models.CharField(default="Відгуки", max_length=64)),
                (
                    "testimonials_title",
                    models.CharField(default="Що кажуть команди", max_length=200),
                ),
                ("faq_kicker", models.CharField(default="FAQ", max_length=64)),
                ("faq_title", models.CharField(default="Часті питання", max_length=200)),
                (
                    "cta_title",
                    models.CharField(default="Спробуйте BugTracker сьогодні", max_length=200),
                ),
                (
                    "cta_subtitle",
                    models.TextField(
                        default="Безкоштовно. Без картки. 5 хвилин на онбординг команди."
                    ),
                ),
                ("cta_primary_text", models.CharField(default="Створити акаунт", max_length=64)),
                ("cta_primary_link", models.CharField(default="/register", max_length=128)),
                ("cta_secondary_text", models.CharField(default="Увійти", max_length=64)),
                ("cta_secondary_link", models.CharField(default="/login", max_length=128)),
                (
                    "footer_brand_text",
                    models.TextField(
                        default="Баг-трекер з фокусом на швидкість, ясність та інтеграції з тим, що ваша команда вже використовує."
                    ),
                ),
                (
                    "footer_copyright",
                    models.CharField(default="Зроблено в Україні 🇺🇦", max_length=120),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Налаштування лендінгу",
                "verbose_name_plural": "Налаштування лендінгу",
            },
        ),
        migrations.CreateModel(
            name="LandingTestimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("position", models.PositiveIntegerField(db_index=True, default=0)),
                ("is_visible", models.BooleanField(default=True)),
                ("quote", models.TextField()),
                ("author_name", models.CharField(max_length=80)),
                ("author_role", models.CharField(max_length=120)),
                ("avatar_initials", models.CharField(default="??", max_length=4)),
                ("avatar_color", models.CharField(default="#5E6AD2", max_length=7)),
                ("featured", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Відгук",
                "verbose_name_plural": "Відгуки",
                "ordering": ["position"],
            },
        ),
        migrations.CreateModel(
            name="LandingUseCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("position", models.PositiveIntegerField(db_index=True, default=0)),
                ("is_visible", models.BooleanField(default=True)),
                ("title", models.CharField(max_length=80)),
                ("description", models.TextField()),
                (
                    "icon",
                    models.CharField(
                        choices=[
                            ("Bug", "🐛 Bug"),
                            ("Beaker", "🧪 Beaker"),
                            ("Play", "▶ Play"),
                            ("Layout", "▦ Layout"),
                            ("Chart", "📊 Chart"),
                            ("Comment", "💬 Comment"),
                            ("Bell", "🔔 Bell"),
                            ("Lightning", "⚡ Lightning"),
                            ("AI", "✨ AI"),
                            ("User", "👤 User"),
                            ("Users", "👥 Users"),
                            ("Github", "Github"),
                            ("Slack", "Slack"),
                            ("Spark", "✦ Spark"),
                            ("Star", "★ Star"),
                            ("Globe", "🌐 Globe"),
                            ("Refresh", "↻ Refresh"),
                            ("Settings", "⚙ Settings"),
                            ("Lock", "🔒 Lock"),
                            ("Activity", "📈 Activity"),
                        ],
                        default="User",
                        max_length=32,
                    ),
                ),
                (
                    "color_variant",
                    models.CharField(
                        choices=[
                            ("accent", "Акцент (фіолетовий)"),
                            ("resolved", "Зелений"),
                            ("progress", "Жовтий"),
                            ("blocked", "Пурпуровий"),
                            ("open", "Червоний"),
                            ("closed", "Сірий"),
                        ],
                        default="accent",
                        max_length=20,
                    ),
                ),
                (
                    "bullets",
                    models.TextField(
                        blank=True, default="", help_text="Список переваг (один пункт на рядок)"
                    ),
                ),
            ],
            options={
                "verbose_name": "Use Case",
                "verbose_name_plural": "Use Cases",
                "ordering": ["position"],
            },
        ),
    ]
