# Generated by Django 5.2.7 on 2026-05-03 11:37

import django.core.validators
import django.db.models.deletion
import landing.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("landing", "0002_clear_text_data"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="landingfaqitem",
            name="is_published",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="landingfeature",
            name="is_published",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="landinghero",
            name="draft_data",
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="landingintegration",
            name="is_published",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="landingintegration",
            name="logo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="landing/integrations/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["png", "jpg", "jpeg", "svg", "webp"]
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="landingmetric",
            name="is_published",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="landingsettings",
            name="draft_data",
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="landingtestimonial",
            name="is_published",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="landingusecase",
            name="is_published",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="landingfaqitem",
            name="answer",
            field=landing.models.TranslatableField(
                blank=True, default=landing.models.empty_translation
            ),
        ),
        migrations.AlterField(
            model_name="landingfaqitem",
            name="question",
            field=landing.models.TranslatableField(
                blank=True, default=landing.models.empty_translation
            ),
        ),
        migrations.AlterField(
            model_name="landingfeature",
            name="description",
            field=landing.models.TranslatableField(
                blank=True, default=landing.models.empty_translation
            ),
        ),
        migrations.AlterField(
            model_name="landingfeature",
            name="title",
            field=landing.models.TranslatableField(
                blank=True, default=landing.models.empty_translation
            ),
        ),
        migrations.AlterField(
            model_name="landinghero",
            name="eyebrow_badge",
            field=models.CharField(default="NEW", max_length=32),
        ),
        migrations.AlterField(
            model_name="landinghero",
            name="eyebrow_text",
            field=landing.models.TranslatableField(
                blank=True, default=landing.models.empty_translation
            ),
        ),
        migrations.AlterField(
            model_name="landinghero",
            name="eyebrow_version",
            field=models.CharField(blank=True, default="v2.0", max_length=32),
        ),
        migrations.AlterField(
            model_name="landinghero",
            name="foot_text_1",
            field=landing.models.TranslatableField(
                blank=True, default=landing.models.empty_translation
            ),
        ),
        migrations.AlterField(
            model_name="landinghero",
            name="foot_text_2",
            field=landing.models.TranslatableField(
                blank=True, default=landing.models.empty_translation
            ),
        ),
        migrations.AlterField(
            model_name="landinghero",
            name="foot_text_3",
            field=landing.models.TranslatableField(
                blank=True, default=landing.models.empty_translation
            ),
        ),
        migrations.AlterField(
            model_name="landinghero",
            name="lede",
            field=landing.models.TranslatableField(
                blank=True, default=landing.models.empty_translation
            ),
        ),
        migrations.AlterField(
            model_name="landinghero",
            name="primary_cta_text",
            field=landing.models.TranslatableField(
                blank=True, default=landing.models.empty_translation
            ),
        ),
        migrations.AlterField(
            model_name="landinghero",
            name="secondary_cta_text",
            field=landing.models.TranslatableField(
                blank=True, default=landing.models.empty_translation
            ),
        ),
        migrations.AlterField(
            model_name="landinghero",
            name="title_a",
            field=landing.models.TranslatableField(
                blank=True, default=landing.models.empty_translation
            ),
        ),
        migrations.AlterField(
            model_name="landinghero",
            name="title_accent",
            field=landing.models.TranslatableField(
                blank=True, default=landing.models.empty_translation
            ),
        ),
        migrations.AlterField(
            model_name="landinghero",
            name="title_b",
            field=landing.models.TranslatableField(
                blank=True, default=landing.models.empty_translation
            ),
        ),
        migrations.AlterField(
            model_name="landingmetric",
            name="label",
            field=landing.models.TranslatableField(
                blank=True, default=landing.models.empty_translation
            ),
        ),
        migrations.AlterField(
            model_name="landingmetric",
            name="value",
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name="landingsettings",
            name="cta_primary_text",
            field=landing.models.TranslatableField(
                blank=True, default=landing.models.empty_translation
            ),
        ),
        migrations.AlterField(
            model_name="landingsettings",
            name="cta_secondary_text",
            field=landing.models.TranslatableField(
                blank=True, default=landing.models.empty_translation
            ),
        ),
        migrations.AlterField(
            model_name="landingsettings",
            name="cta_subtitle",
            field=landing.models.TranslatableField(
                blank=True, default=landing.models.empty_translation
            ),
        ),
        migrations.AlterField(
            model_name="landingsettings",
            name="cta_title",
            field=landing.models.TranslatableField(
                blank=True, default=landing.models.empty_translation
            ),
        ),
        migrations.AlterField(
            model_name="landingsettings",
            name="faq_kicker",
            field=landing.models.TranslatableField(
                blank=True, default=landing.models.empty_translation
            ),
        ),
        migrations.AlterField(
            model_name="landingsettings",
            name="faq_title",
            field=landing.models.TranslatableField(
                blank=True, default=landing.models.empty_translation
            ),
        ),
        migrations.AlterField(
            model_name="landingsettings",
            name="features_kicker",
            field=landing.models.TranslatableField(
                blank=True, default=landing.models.empty_translation
            ),
        ),
        migrations.AlterField(
            model_name="landingsettings",
            name="features_subtitle",
            field=landing.models.TranslatableField(
                blank=True, default=landing.models.empty_translation
            ),
        ),
        migrations.AlterField(
            model_name="landingsettings",
            name="features_title",
            field=landing.models.TranslatableField(
                blank=True, default=landing.models.empty_translation
            ),
        ),
        migrations.AlterField(
            model_name="landingsettings",
            name="footer_brand_text",
            field=landing.models.TranslatableField(
                blank=True, default=landing.models.empty_translation
            ),
        ),
        migrations.AlterField(
            model_name="landingsettings",
            name="footer_copyright",
            field=landing.models.TranslatableField(
                blank=True, default=landing.models.empty_translation
            ),
        ),
        migrations.AlterField(
            model_name="landingsettings",
            name="integrations_kicker",
            field=landing.models.TranslatableField(
                blank=True, default=landing.models.empty_translation
            ),
        ),
        migrations.AlterField(
            model_name="landingsettings",
            name="integrations_subtitle",
            field=landing.models.TranslatableField(
                blank=True, default=landing.models.empty_translation
            ),
        ),
        migrations.AlterField(
            model_name="landingsettings",
            name="integrations_title",
            field=landing.models.TranslatableField(
                blank=True, default=landing.models.empty_translation
            ),
        ),
        migrations.AlterField(
            model_name="landingsettings",
            name="testimonials_kicker",
            field=landing.models.TranslatableField(
                blank=True, default=landing.models.empty_translation
            ),
        ),
        migrations.AlterField(
            model_name="landingsettings",
            name="testimonials_title",
            field=landing.models.TranslatableField(
                blank=True, default=landing.models.empty_translation
            ),
        ),
        migrations.AlterField(
            model_name="landingsettings",
            name="use_cases_kicker",
            field=landing.models.TranslatableField(
                blank=True, default=landing.models.empty_translation
            ),
        ),
        migrations.AlterField(
            model_name="landingsettings",
            name="use_cases_subtitle",
            field=landing.models.TranslatableField(
                blank=True, default=landing.models.empty_translation
            ),
        ),
        migrations.AlterField(
            model_name="landingsettings",
            name="use_cases_title",
            field=landing.models.TranslatableField(
                blank=True, default=landing.models.empty_translation
            ),
        ),
        migrations.AlterField(
            model_name="landingtestimonial",
            name="author_role",
            field=landing.models.TranslatableField(
                blank=True, default=landing.models.empty_translation
            ),
        ),
        migrations.AlterField(
            model_name="landingtestimonial",
            name="quote",
            field=landing.models.TranslatableField(
                blank=True, default=landing.models.empty_translation
            ),
        ),
        migrations.AlterField(
            model_name="landingusecase",
            name="bullets",
            field=landing.models.TranslatableField(
                blank=True, default=landing.models.empty_translation
            ),
        ),
        migrations.AlterField(
            model_name="landingusecase",
            name="description",
            field=landing.models.TranslatableField(
                blank=True, default=landing.models.empty_translation
            ),
        ),
        migrations.AlterField(
            model_name="landingusecase",
            name="title",
            field=landing.models.TranslatableField(
                blank=True, default=landing.models.empty_translation
            ),
        ),
        migrations.CreateModel(
            name="LandingChangeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("object_id", models.PositiveIntegerField(blank=True, null=True)),
                ("model_name", models.CharField(max_length=64)),
                ("object_label", models.CharField(blank=True, max_length=200)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("created", "Створено"),
                            ("updated", "Оновлено"),
                            ("deleted", "Видалено"),
                            ("published", "Опубліковано"),
                            ("unpublished", "Знято з публікації"),
                            ("published_draft", "Чорновик опубліковано"),
                            ("draft_discarded", "Чорновик скасовано"),
                        ],
                        max_length=20,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("data_snapshot", models.JSONField(blank=True, default=None, null=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Запис журналу",
                "verbose_name_plural": "Журнал змін",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["model_name", "-timestamp"], name="landing_lan_model_n_097421_idx"
                    ),
                    models.Index(
                        fields=["content_type", "object_id", "-timestamp"],
                        name="landing_lan_content_a9c58e_idx",
                    ),
                ],
            },
        ),
    ]
